scalar DateTime
scalar Email
scalar URL
scalar LimitString
scalar Password

input AddArticleInput {
	title: String!
	text: String!
	category: ArticleCategory=OTHER
}

input EditArticleInput {
	articleId: ID!
	title: String
	text: String
	views: Int
	category: ArticleCategory=OTHER
}

input AddCommentInput {
	articleId: ID!
	username: String!
	text: String!
}

enum ArticleCategory{
	GAMES
	NEWS
	OTHER
}

type File {
	filename: String
	mimetype: String
	encoding: String
}

type Comment {
	_id: ID!
	articleId: String!
	username: String!
	text: String!
	created_at: DateTime!
}

type Article {
	_id: ID!
	title: String!
	text: String!
	views: Int!
	image: String!
	category: ArticleCategory
	comments: [Comment]
	created_at: DateTime!
}

type Query {
	totalArticles: Int!
	articles(first: Int=10): [Article!]!
	article(articleId: ID!): Article!
}

type Mutation {
	addArticle(input: AddArticleInput!): Article!
	editArticle(input: EditArticleInput!): Article!
	removeArticle(articleId: ID!): Article!
	addComment(input: AddCommentInput!): Comment!
}

type Subscription {
	newComment: Comment!
}
