scalar Email
scalar DateTime

type UserAvatar {
	color: String!
	images: [String!]!
}
type User {
	_id: String!
	email: Email!
	firstName: String!
	lastName: String
	username: String
	avatar: UserAvatar!
	bookmarks: [ID!]!
}

type Comment {
	_id: String!
	text: String!
	user: User!
	replies: [Comment!]!
	created: DateTime!
}

type Article {
	_id: ID!
	title: String!
	text: String!
	image: String!
	images: [String!]!
	slug: String!
	views: Int!
	likes: Int!
	dislikes: Int!
	created: DateTime!
	comments: [Comment!]!
	user: User!
}

type ArticleStatistics {
	labels: [String!]!
	views: [Int!]!
	comments: [Int!]!
}

type UserOnline {
	userId: ID!
	online: Boolean!
}

# all queries
type Query {
	allArticles: [Article!]!
	allUsers: [User!]!
	Article(id: String!): Article!

	topTags: [String!]!
	topArticles(limit: Int = 5): [Article!]!

	articleStatistics: ArticleStatistics!
	userBookmarks(userId: ID!): [Article!]!
	userFeed(userId: ID!): [Article!]!

	userOnline(userId: ID!): UserOnline!
}

# all mutations
type Mutation {
	addLike(id: ID!): Boolean!
	addDislike(id: ID!): Boolean!
	addView(id: ID!): Boolean!
	addToBookmarks(articleId: ID!, userId: ID!): Boolean!

	startSession: Boolean!
	endSession: Boolean!
}

# all subscriptions
type Subscription {
	likeAdded: Article!
	dislikeAdded: Article!
	viewAdded: Article!

	userOnline(userId: ID!): UserOnline!
}
